[package]
name = "op"
version = "0.0.0"

[dependencies]
MinitiaStdlib = { git = "https://github.com/initia-labs/initiavm.git", subdir = "crates/../precompile/modules/minitia_stdlib", rev = "main" }

[addresses]
std =  "0x1"
minitia_std = "0x1"
addr = "0x56ccf33c45b99546cd1da172cf6849395bbf8573"
